import pandas as pd

# Creation of the database for the application
# database_to_dict = json_to_dict('path')

database_v1: list = [{'Company Name': 'TechCorp', 
             'Industry': 'Technology', 
             'Market Capitalization': '5000', 'Revenue (in millions)': '1500',
             'EBITDA (in millions)': '300', 'Net Income (in millions)': '100', 
             'Debt (in millions)': '200', 'Equity (in millions)': '800', 
             'Enterprise Value (in millions)': '5400', 'P/E Ratio': '25', 
             'Revenue Growth Rate (%)': '10', 'EBITDA Margin (%)': '20', 
             'Net Income Margin (%)': '6.67', 
             'ROE (Return on Equity) (%)': '12.5', 
             'ROA (Return on Assets) (%)': '7.5', 
             'Current Ratio': '2.5', 
             'Debt to Equity Ratio': '0.25', 
             'Location': 'San Francisco'}, 
            
            {'Company Name': 'HealthInc', 
             'Industry': 'Healthcare', 
             'Market Capitalization': '3000', 
             'Revenue (in millions)': '1000', 
             'EBITDA (in millions)': '250', 
             'Net Income (in millions)': '80', 
             'Debt (in millions)': '150', 
             'Equity (in millions)': '600', 
             'Enterprise Value (in millions)': '3150', 
             'P/E Ratio': '15', 
             'Revenue Growth Rate (%)': '12', 
             'EBITDA Margin (%)': '25', 
             'Net Income Margin (%)': '8', 
             'ROE (Return on Equity) (%)': '13.33', 
             'ROA (Return on Assets) (%)': '10', 
             'Current Ratio': '2', 
             'Debt to Equity Ratio': '0.25', 
             'Location': 'New York'}, 
             
             {'Company Name': 'RetailCo', 
              'Industry': 'Retail', 
              'Market Capitalization': '2000', 
              'Revenue (in millions)': '800', 
              'EBITDA (in millions)': '150', 
              'Net Income (in millions)': '40', 
              'Debt (in millions)': '100', 
              'Equity (in millions)': '400', 
              'Enterprise Value (in millions)': '2100', 
              'P/E Ratio': '20', 
              'Revenue Growth Rate (%)': '8', 
              'EBITDA Margin (%)': '18.75', 
              'Net Income Margin (%)': '5', 
              'ROE (Return on Equity) (%)': '10', 
              'ROA (Return on Assets) (%)': '6.5', 
              'Current Ratio': '1.8', 
              'Debt to Equity Ratio': '0.25', 'Location': 'Chicago'}, 
              
              {'Company Name': 'FinanceLLC', 
               'Industry': 'Financial Services', 
               'Market Capitalization': '4000', 
               'Revenue (in millions)': '1200', 
               'EBITDA (in millions)': '400', 
               'Net Income (in millions)': '150', 
               'Debt (in millions)': '300', 
               'Equity (in millions)': '1000', 
               'Enterprise Value (in millions)': '4300', 
               'P/E Ratio': '18', 
               'Revenue Growth Rate (%)': '15', 
               'EBITDA Margin (%)': '33.33', 
               'Net Income Margin (%)': '12.5', 
               'ROE (Return on Equity) (%)': '20', 
               'ROA (Return on Assets) (%)': '12', 
               'Current Ratio': '3', 
               'Debt to Equity Ratio': '0.3', 
               'Location': 'Boston'}, 
               
               
               {'Company Name': 'ManuCorp', 
                'Industry': 'Manufacturing', 
                'Market Capitalization': '2500', 
                'Revenue (in millions)': '900', 
                'EBITDA (in millions)': '200', 
                'Net Income (in millions)': '60', 
                'Debt (in millions)': '200', 
                'Equity (in millions)': '500', 
                'Enterprise Value (in millions)': '2700', 
                'P/E Ratio': '22', 
                'Revenue Growth Rate (%)': '9', 
                'EBITDA Margin (%)': '22.22', 
                'Net Income Margin (%)': '6.67', 
                'ROE (Return on Equity) (%)': '12', 
                'ROA (Return on Assets) (%)': '8', 
                'Current Ratio': '2.2', 
                'Debt to Equity Ratio': '0.4', 
                'Location': 'Dalla'}]

# db1 -> each company is a has a company name as key
database_v1_dict: dict = {company['Company Name']: company for company in database_v1}


